version: '3.6'

networks:
  internal:

services:
  database:
    image: postgres:14.1-alpine3.14
    restart: always
    ports:
      - 5432:5432
    networks:
       - internal
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      
  adminer:
    image: adminer
    restart: always
    networks:
       - internal
    ports:
      - 8080:8080


